### PR TITLE
Update test workflow

### PR DESCRIPTION
**Pull request by sondrelg**
## Changes
- Adds django matrix with supported package versions and python 3.9 to the test workflow 🚀
- Removes unnecessary isort config
- Updates package metadata to include python 3.9 and django 3.1

### CODE REVIEW

**Comment by JonasKs** [comment]
S e x y🤩 I’ll look more closely when I get home, but this all looks awesome!

**Comment by sondrelg** [comment]
It's also possible to use pre-commit for linting checks instead of black+isort+flake8, and configure a pre-commit cache.

and I was hoping to configure test to run on pushes to master *or* pull requests, but seems that's not possible, so think I'll revert to `pull_request` only. Do you agree?

**Comment by sondrelg** [comment]
All in all I think we increase the test runtime by ~30 seconds

image

but now there's a dedicated job for each combination of all supported python and django versions, as documented in the packages metadata + a linting job to make sure any new code is consistent.

image

**Comment by JonasKs** [comment]
Do you want to update this to use your action before merging?

**Review by JonasKs — APPROVED** [review]

**Pull request merged**
